-- TODO: Set up formatter(s)
-- TODO: Set up LSP(s)
-- TODO: Set up project root identifier
-- TODO: Set up linters
-- TODO: Other specific utils
-- TODO: Figure out how to handle different kind of projects in the same language
